name: Build Android APK1
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Licenses and Install SDK Packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Build APK
        run: |
          ./gradlew :app:assembleDebug || gradle :app:assembleDebug --gradle-version 8.7

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Sms2Bark-APK
          path: app/build/outputs/apk/debug/*.apk
