name: Build Android APK
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # 安装 Android SDK（命令行工具 + 必需包）
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # 没有 gradlew 也能构建（由 action 提供 Gradle 8.7）
      - name: Build APK (Debug)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: :app:assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sms2Bark-APK
          path: app/build/outputs/apk/debug/*.apk
